### PR TITLE
handle double backslash

### PR DESCRIPTION
**Pull request by hokuda**
Fix for https://issues.jboss.org/browse/WFCORE-1868

### CODE REVIEW

**Comment by jfdenise** [comment]
Could you hold a bit for the merge, we can't reproduce this issue with latest WildFly Core CLI although the original bug has been logged against it: https://issues.jboss.org/browse/WFCORE-1868

**Comment by hokuda** [comment]
@jfdenise  I confirmed the issue is not reproduced in wildfly-core 3.0.0.x of https://github.com/jfdenise/wildfly-core/tree/WFCORE-1878. However, I'd like to merge this, because:
* EAP7.0.x is still based on wildfly-core 2.0.x and not guaranteed to move to wildfly-core 3.0.
* this fix is good for other aesh application.
* this is harmless to wildfly-core 3.0.

**Comment by jfdenise** [comment]
We have understood what is going on, I have no issue with this fix being added to Aesh.

**Comment by stalep** [comment]
thanks!

**Pull request merged**
