### PR TITLE
Align command name and command description and add color

### PR DESCRIPTION
**Pull request by thescouser89**
aesh-output

This commit aligns the command names and the command description, and adds a dash of color to the command name (can be disabled by calling updateAnsiMode(false))

### CODE REVIEW

**Comment by thescouser89** [comment]
@stalep Could you push the changes that went into v2.2 to the master branch also? If that creates merge conflicts I'll rebase :)

**Comment by stalep** [comment]
Dang, I forgot to push... - really sorry about that, pushed now!
I like the change, but i was wondering if it would make sense to change the entire StringBuilder with the new AnsiBuilder? (org.aesh.util.ANSIBuilder).
I thought the ANSI class was a bit cumbersome to use, so I created ANSIBuilder which (hopefully) is a bit easier to use.

**Comment by thescouser89** [comment]
I wasn't aware of AnsiBuilder! Was just using the the Option string as an example. I'll rebase and try ANSIBuilder and I'll adjust my PR. Thanks for the suggestion! :)

**Comment by stalep** [comment]
Hm, I see that adding a .disableAnsi() for ANSIBuilder would probably be helpful here... Perhaps that could be useful?

**Comment by thescouser89** [comment]
Yup! Then we could just use Ansibuilder and disable color with just a method!

**Comment by stalep** [comment]
I made some changes to aesh-readline and deployed a 1.16-SNAPSHOT which has the changes we talked about.

**Comment by thescouser89** [comment]
@stalep I've rebased to use ANSIBuilder for command line! :) Thanks for the changes on aesh-readline!

**Pull request merged**
