### PR TITLE
methods to get center width and height plus javadoc.

### PR DESCRIPTION
**Pull request by eprogramming**

### CODE REVIEW

**Comment by danielsoro** [comment]
Nice. Can you create test to it!?

On Wednesday, January 28, 2015, Helio Frota <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/aeshell/aesh/pull/143
> Commit Summary
>
>    - methods to get center width and height plus javadoc.
>
> File Changes
>
>    - *M* src/main/java/org/jboss/aesh/terminal/TerminalSize.java
>    <https://github.com/aeshell/aesh/pull/143/files#diff-0> (41)
>
> Patch Links:
>
>    - https://github.com/aeshell/aesh/pull/143.patch
>    - https://github.com/aeshell/aesh/pull/143.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aeshell/aesh/pull/143>.
>


-- 
Daniel Cunha (soro)

**Comment by eprogramming** [comment]
sure

**Comment by danielsoro** [comment]
You're awesome. Thank you for understanding . :)

On Wednesday, January 28, 2015, Helio Frota <notifications@github.com>
wrote:

> sure
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aeshell/aesh/pull/143#issuecomment-71935770>.
>


-- 
Daniel Cunha (soro)

**Comment by stalep** [comment]
thanks!

**Pull request merged**
