### PR TITLE
[AESH-316] - print warning instead of exception on unsupported C-

### PR DESCRIPTION
**Pull request by baranowb**
https://issues.jboss.org/browse/AESH-316

### CODE REVIEW

**Comment by stalep** [comment]
thanks, this looks good. ill accept the pr for master since there might be other chars thats not supported. atm this is only a fix for 0.60, not for 0.33.* since that is based on the eap branch.

**Comment by stalep** [comment]
you need to rebase with the up to date master before ill accept the pr however.

**Comment by baranowb** [comment]
whoops. it seems I ^-Ced  rebase for some reason and it did not happen...

**Comment by stalep** [comment]
thanks!

**Comment by stalep** [comment]
thanks!

**Pull request merged**
