### PR TITLE
[AESH-318] "Aesh Executor Service" thread leaks

### PR DESCRIPTION
**Pull request by jerr**
Force shutdown of the Executor Service.

### CODE REVIEW

**Comment by stalep** [comment]
hi, i think the .stop() call is good, but im not sure if the shutdownNow() is correct? especially if we dont use the return list for anything. whats the reason to use shutdown()? - not saying i wont accept it, i just want to understand :)

**Comment by jerr** [comment]
Hi stalep,

In our case, the shutdown() has not much use. It is used to remove all pending tasks. But here we have just one running task and it is this that we want to stop.

So, shutdownNow() do the job (and it corrects the thread leaks problem)  but we can find another way.
Hope this helps.

Regards,
Jérémie.

**Comment by stalep** [comment]
i agree, i just dont understand why the thread doesnt finish on its own. if this fixes the problem of the leak then we should have it in. - it all boils down to that InputStream.read() doesnt exit even if the thread is interrupted...
i updated the file when i changed the logging, do you want to update the pr or should i just manually do the same thing as in this pr?

**Comment by stalep** [comment]
hi, i just wanted to get this in so i just commited it myself. didnt mean to snipe your pr though. thanks a lot for your work! :)

**Comment by stalep** [comment]
hm, with shutdownNow() we get a lot of interruptedExceptions:
    java.io.InterruptedIOException
    	at java.io.PipedInputStream.read(PipedInputStream.java:328)
    	at java.io.PipedInputStream.read(PipedInputStream.java:377)
    	at java.io.InputStream.read(InputStream.java:101)
    	at org.jboss.aesh.console.reader.AeshInputStream.readFromStream(AeshInputStream.java:106)
    	at org.jboss.aesh.console.reader.AeshInputStream.readAll(AeshInputStream.java:51)
    	at org.jboss.aesh.console.reader.ConsoleInputSession$2.run(ConsoleInputSession.java:69)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)

are you still sure we get thread leaks?

**Comment by jerr** [comment]
If you have an interrupt exception on .AeshInputStream.readAll() it means that you are in the case of a thread leak. We want to stop this thread. 
I will look to better manage exceptions and the stop method.

**Comment by jerr** [comment]
Hi stalep,

I test your code, It seems that you also remove the leaks, but a dead lock appeared between : 
  - user thread on console.stop() 
  - and "AeshProcess" thread on org.jboss.forge.furnace.impl.addons.AddonStateManager.getState() L155

For me is the last big issue before valide the new aesh version in jboss forge.
If you need help with this, we can contact us on irc.

Regards,
Jérémie.

**Comment by stalep** [comment]
hm, if you can give me a better understanding of why there is a deadlock that would be great! :)
the Console.doStop() method is synchronized so that can i theory create a deadlock if that method i waiting on something which again tries to get a lock on the same method, but atm i cant see how this can happen.

**Comment by jerr** [comment]
Hi stalep,
With your last commit, the method doStop() is never call, so we have lots of leaks.
I'll try to give you a code tomorrow by taking the part that eliminates leaks and your code to avoid the deadlock.

Regards,
Jeremie.

**Comment by stalep** [comment]
hm, I can't understand how that is possible.
stop() sets a variable that should be picked up by the reader thread. the
reason I changed it was to prevent the command/process thread to do the
stop.

if the reader thread isn't picking it up something is very wrong.

ståle

**Comment by stalep** [comment]
please let me know how you can reproduce this.

**Comment by jerr** [comment]
Hi stalep,

To test it I use the test of javaee forge module. Just "run mvn" test and inspect threads via visualvm or atach your edi debugger.  

I undo my rebase of the AESH-318 branch and add your code with counter to prevent deadlock. With this version all aesh thread leaks and deadlock are removed. Thanks for your help!

Regards,
Jérémie.

**Comment by stalep** [comment]
ah, that's great. thanks for reporting and testing!

**Comment by jerr** [comment]
Hi Stale and Daniel,

Do not forget to merge the code with the branch AESH-318 to correct the problem.

On the master branch leaks are still here, in addition, the other thread leaks reappeared. (see my previous comments)

When I run jboss forge javaee module test with the aesh master branch :  
image 
Leaks are still here :(


The same with my pull request :
image

No Aesh thread leaks in this case. 

Regards,
Jérémie.

**Comment by danielsoro** [comment]
Sorry!

I thought that is ok with last comments.

**Comment by danielsoro** [comment]
Stale is checking that. :)

**Comment by stalep** [comment]
ok, i thought that master was working for you. afaik the only difference is that master is not calling .shutdownNow(), but shutdown().
ive updated master, can you please test again?

**Comment by stalep** [comment]
- or can you update your pr with the latest changes to master then i can properly merge :)

**Comment by jerr** [comment]
Hi Stale,
Your modification of shutdown() to shutdownNow() can not work and the last commit in master.
When I rebased my PR on the master code, the stop the method was no longer called.
I was forced to cancel my rebase (it's a good git exercise). This is why the PR is not on the latest master version but on the version that corrects the problem.

Regards,
Jérémie.

**Comment by stalep** [comment]
hm, i cant understand why this is not working. is the forge master working
with the latest master of æsh?
if so ill try to test this tomorrow.
whats the "difference" between your pr and whats in æsh master atm?

**Comment by jerr** [comment]
Hi Stale,

It seems that the master branch is correct. It is no longer necessary to merge with this pull request.
Hope to have a new released version soon. ;)

Regards,
Jérémie.

**Comment by stalep** [comment]
hi, thats great! i was hoping the last changes would have a positive impact.
the pr now seems to clean up a few things which i dont mind so ill gladly merge it, im a bit uncertain about the blockingQueue.put(NULL_INPUT) in ConsoleInputSession since it didnt have any effect afaik. thanks for your patience! :)

**Pull request merged**
