### PR TITLE
Low level console API

### PR DESCRIPTION
**Pull request by gnodet**
This PR is about bringing a cleaner and more powerful very low level API for terminals.
It supports signals support, infocmp terminals, stty settings (with some level of emulation on Windows) and virtual terminal support.

The first commit is about full infocmp support, which is mandatory for supporting external consoles (where their terminals may not be the one where Aesh is running).

The second commit brings the new api and implementation.

The api/impl/utils packages are self-contained (but a dependency on LoggerUtils for better integration) so that it can be moved / refactored easily.
The one entry point is really the ConsoleBuilder.

### CODE REVIEW

**Comment by gnodet** [comment]
Well, the test do work, but the CI is setup to build on JDK7, which obviously fail because the requirement is JDK8.

**Comment by stalep** [comment]
thanks!
i had to do a couple of changes to get it to work. i had to change the -f option on stty to -F. is it a typo or on my system that stty requires -F instead? (im using fedora 22).
enter is now mapped to int 13, i had to just map CTRL_M to NEW_LINE to get it initially to work. is it deliberate that its now mapped to 13?
thanks again!

**Comment by stalep** [comment]
- travis should now only build on jdk8

**Comment by stalep** [comment]
ah, yes. i noticed that some of the files had the bsd license header. can you please change it to apache?

**Pull request merged**
