### PR TITLE
Bad behaviours

### PR DESCRIPTION
**Pull request by gnodet**
These unit tests show some problematic behaviours in AEsh

### CODE REVIEW

**Comment by gnodet** [comment]
Yeah, well, the tests fail as expected ;-)

**Comment by stalep** [comment]
Hi, thanks for the pr. could you please split up the pr into several?
I don't have any problems merging the Operation,AeshInputProcessor.parseOperation change. Atm we've not accepted pr's that fail deliberately, but I see your point.
Yes, Console.getCursor() is problematic, it has not been reported as an issue, but as you demostrate it can be. We only use it to get the current row of the cursor. We can do this when the shell starts and we should not need to fetch it again.

**Comment by stalep** [comment]
regarding the keyParsingTest() i see that æsh behaves differently than bash. bash seems to store the esc if its found at the end of the inputstream in emacs mode. we can change æsh to behave similar

**Comment by stalep** [comment]
we can add a setting to disable the check for open quotes.

**Pull request closed without merging**
